### PR TITLE
Fixing Client.cancel_document()

### PR DESCRIPTION
**Pull request by ndjdev**
Fix for #6

### CODE REVIEW

**Comment by ndjdev** [comment]
Any chance of getting this merged or letting me know what's wrong with it? Thanks

**Comment by dominikkukacka** [comment]
Sorry, we overlooked the PR. LGTM

**Comment by dominikkukacka** [comment]
Thank you very much!

**Comment by ndjdev** [comment]
@dominikkukacka Any chance you could release version 1.1.2 with this fix in to PyPi so we can stop using our fork link in our requirements files? Thanks

**Comment by dominikkukacka** [comment]
Sure. https://pypi.org/project/eversign/1.1.2/
Thanks again!

**Comment by ndjdev** [comment]
Thanks @dominikkukacka !

**Pull request merged**
