### PR TITLE
fix-sandbox-value-type

### PR DESCRIPTION
**Pull request by karlloic**
The datatype for this seems to be integer type. I tested with bool and it cost me 1 API document credit

### CODE REVIEW

**Comment by milanlatinovic** [comment]
Hi @karlloic, is this MR really solving issue for you?

I checked Python SDK code and seems like both Integer and Boolean types are supported.
For example if you try to create common document (create_document.py) with document.sandbox = 1 or document.sandbox.True both are working nice.

On the other side, when I tried to create Template Document as Sandbox, neither = 1 or = True helped.

I am thinking this might be problem with Eversign API, not with the SDK.

What are your thoughts on this? 

Thanks,
Milan

**Comment by karlloic** [comment]
Hi @milanlatinovic,  

Yes I agree. This makes sense. Over the weekend I noticed the same thing. It is currently NOT possible to create a document from template as Sandbox. At first I thought it was a bool/int issue just because my account dashboard didn't get updated right away but I can now confirm that neither 1 nor True work. The SDK seems fine but the API might not be capturing that value. So the MR will probably not solve the issue. 

Thanks,
Karl

**Comment by milanlatinovic** [comment]
Hi @karlloic, 

Yes, that makes sense, thanks for quick feedback.
I will close this MR because SDK works properly, and I will open ticket for Eversign API so that someone look into this issue.
If this is causing you issues in testing you can contact our support at Eversign with account details.

Kind regards,
Milan

**Review by milanlatinovic — COMMENTED** [review]
After reviewing this we concluded that this is not solving original issue.
Actually, issue is not Python SDK related, but Eversign API related, and it was reported.

**Comment by milanlatinovic** [comment]
Hi @karlloic,

After revisiting this issue once more, it was Python SDK issue.
Client was not supporting sandbox parameter at all.

This is fixed now, and new release is created here
https://github.com/eversign/eversign-python-sdk/releases/tag/1.2.1

Please, use new release and you will not have problems any more :) 
Cheers, and thanks for reporting this in the first place!

**Comment by karlloic** [comment]
@milanlatinovic Great! Thanks for the fix. When will this release be published to pypi?

**Comment by milanlatinovic** [comment]
@karlloic sorry for a delay, I lost this thread out of my sight since it was closed. :)

I made a new release today https://pypi.org/project/eversign/1.2.2/

If any other issues, please reopen the ticket so it will be more visible.
You can also followup on twitter, #eversign tag as well for news about new releases and features.

Happy holidays and stay safe.

**Comment by karlloic** [comment]
Thank you @milanlatinovic 
Happy Holidays!

**Pull request closed without merging**
